default_link: "http://wattlecourses.anu.edu.au"
default_semester: 1
default_year: 2019
hours:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
weekdays:
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
weeks:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
week_to_second: 604800
